module.exports = function (actions,tags) {
  describe('Access Page', function () {
    describe('', function () {
      actions.logout();
      actions.iAmLoggedInFor('accessProj');
      actions.goToPage('#/');
      actions.projectExisting('New Project', 'This is a test project');
      actions.clickOnElementWithText('New Project');
      actions.clickOnElementWithText('Access');
      actions.iSeeTextCount('Administrator', 5);
      actions.iSeeTextCount('Authenticated', 3);
      actions.iSeeTextCount('Anonymous', 3);
      actions.clickOnClassWithIndex('.ui-select-search', 0);
      actions.clickOnElementWithText('Anonymous');
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.ui-select-search', 2);
      actions.clickOnElementWithTextIndex('Authenticated', 1);
      actions.clickOnClass('.toast-message');
      actions.pageReload();
      actions.iSeeTextCount('Administrator', 5);
      actions.iSeeTextCount('Authenticated', 4);
      actions.iSeeTextCount('Anonymous', 4);
    });
    tags('smoke').describe('',function() {
      actions.enterTextInField('#form-search', 'Lo');
      actions.iSeeText('User Login');
      actions.iDonotSeeText('User Register');
      actions.iSeeText('Admin Login');
      actions.enterTextInField('#form-search', 'R');
      actions.iSeeText('User Login');
      actions.iSeeText('User Register');
      actions.iDonotSeeText('Admin Login');
      actions.enterTextInField('#form-search', 'Z');
      actions.iDonotSeeText('User Login');
      actions.iDonotSeeText('User Register');
      actions.iDonotSeeText('Admin Login');
      actions.enterTextInField('#form-search', '');
      actions.iSeeText('User Login');
      actions.iSeeText('User Register');
      actions.iSeeText('Admin Login');
      actions.enterTextInField('#resource-search', 'Us');
      actions.iSeeText('User');
      actions.iDonotSeeText('Admin');
      actions.enterTextInField('#resource-search', 'A');
      actions.iDonotSeeText('User');
      actions.iSeeText('Admin');
      actions.enterTextInField('#resource-search', 'Z');
      actions.iDonotSeeText('Admin');
      actions.iDonotSeeText('User');
      actions.enterTextInField('#resource-search', '');
      actions.iSeeText('Admin');
      actions.iSeeText('User');
      actions.clickOnElementWithText(' Edit Form Access');
      actions.checkingUrlEndsWith('/permission');
      actions.iSeeText('User Login Form ');
      actions.clickOnElementWithText('Access');
      actions.clickOnClass('.glyphicon.glyphicon-trash');
      actions.iSeeText('Are you sure you wish to delete the role ');
      actions.iSeeText('Administrator');
      actions.clickOnElementWithText('Yes');
      actions.iSeeTextIn('.toast-message', 'The Administrator role is required. This can be renamed but not deleted, because it is the role assigned to unauthenticated users.');
      actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('No');
      actions.clickOnClassWithIndex('.glyphicon.glyphicon-trash', 1);
      actions.iSeeText('Are you sure you wish to delete the role ');
      actions.iSeeText('Anonymous');
      actions.clickOnElementWithText('Yes');
      actions.iSeeTextIn('.toast-message', 'The Anonymous role is required. This can be renamed but not deleted, because it is the role assigned to unauthenticated users.');
      actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('No');
      actions.clickOnClassWithIndex('.glyphicon.glyphicon-trash', 2);
      actions.iSeeText('Are you sure you wish to delete the role ');
      actions.iSeeText('Authenticated');
      actions.clickOnElementWithText('No');
      actions.checkingUrlEndsWith('/access');
      actions.iSeeText('Authenticated');
      actions.clickOnClassWithIndex('.glyphicon.glyphicon-trash', 2);
      actions.iSeeText('Are you sure you wish to delete the role ');
      actions.iSeeText('Authenticated');
      actions.clickOnElementWithText('Yes');
      actions.clickOnClass('.toast-message');
      actions.iDonotSeeText('Authenticated');
    });
    describe('',function() {
      actions.clickOnElementWithText(' New Role');
      actions.checkingUrlEndsWith('/roles//edit');
      actions.clickOnElementWithText('Cancel');
      actions.checkingUrlEndsWith('/access');
      actions.clickOnElementWithText(' New Role');
      actions.btnDisabled('Create Role');
      actions.enterTextInField('#title', 'TestingRole');
      actions.enterTextInField('#description', 'Test description of TestingRole.');
      actions.clickOnElementWithText('Create Role');
      actions.clickOnClass('.toast-message');
      actions.iSeeText('TestingRole');
      actions.iSeeText('Test description of TestingRole.');
      actions.clickOnClassWithIndex('.ui-select-search', 0);
      actions.clickOnElementWithText('TestingRole');
      actions.clickOnClass('.toast-message');
      actions.iSeeTextCount('TestingRole',3);
    });
    tags('smoke').describe('',function(){
      actions.clickOnElementWithTextIndex(' Edit',2);
      actions.enterTextInField('#title','Updated TestingRole');
      actions.enterTextInField('#description','Updated Test description of TestingRole.');
      actions.clickOnElementWithText('Save Changes');
      actions.clickOnClass('.toast-message');
      actions.iSeeText('Updated TestingRole');
      actions.iSeeText('Updated Test description of TestingRole.');
      actions.clickOnElementWithTextIndex(' Edit',2);
      actions.clickOnElementWithText('Advanced Settings');
      actions.iSeeValueInContains('#machineName','testingRole');
      actions.enterTextInField('#machineName','updatedMachineName');
      actions.clickOnElementWithText('Save Changes');
      actions.clickOnClass('.toast-message');
      actions.waitForActionToComplete(500);
      actions.pageReload();
      actions.clickOnElementWithText('Advanced Settings');
      // actions.iSeeValueIn('#machineName','updatedMachineName');
      actions.clickOnElementWithText('Save Changes');
      actions.clickOnClassWithIndex('.ui-select-search', 0);
      actions.clickOnElementWithText('Updated TestingRole');
      actions.clickOnClass('.toast-message');
      actions.iSeeTextCount('Updated TestingRole',3);
      actions.clickOnElementWithText(' Edit Form Access');
      actions.checkingUrlEndsWith('/permission');
      actions.iSeeText('User Login Form ');
      actions.clickOnClassWithIndex('.ui-select-search', 0);
      actions.clickOnElementWithText('Updated TestingRole');
      actions.clickOnClass('.toast-message');
      actions.iSeeTextCount('Updated TestingRole',2);
      actions.clickOnElementWithText('Access');
      actions.clickOnElementWithTextIndex(' Edit',2);
      actions.iSeeText(' Create Own Submissions');
      actions.clickOnElementWithText('Save Changes');
      actions.clickOnElementWithText(' Edit Form Access');
      actions.clickOnElementWithText(' Actions');
      actions.clickOnElementWithText('Select an Action');
      actions.clickOnElementWithText('Role Assignment');
      actions.clickOnElementWithText(' Add Action');
      actions.clickOnElementWithText('Select the type of resource to perform role manipulation.');
      actions.clickOnElementWithText('Existing Resource');
      actions.clickOnElementWithText('Select whether this Action will Add or Remove the contained Role.');
      actions.clickOnElementWithText('Add Role');
      actions.clickOnElementWithText('Select the Role that this action will Add or Remove.');
      actions.clickOnElementWithText('Updated TestingRole');
      actions.waitForActionToComplete(500);
      actions.clickOnElementWithText('Save Action');
      actions.clickOnClass('.toast-message');
      actions.logout();
    });
  });
}
