module.exports = function (actions,tags) {
  describe('Adding Stages',function(){
    describe('Testing Adding/Removing Environments',function() {
      actions.logout();
      actions.iAmLoggedInFor('profileuser2');
      actions.goToPage('#/');
      actions.projectExisting('testProject', 'This is a test project');
      actions.clickOnElementWithText('testProject');
      actions.clickOnElementWithText('Forms');
      actions.checkingUrlEndsWith('/form/');
      actions.clickOnElementWithText(' New Form');
      actions.clickOnElementWithText('API Web Form');
      actions.enterTextInField('#title', 'Test Form');
      actions.dragTo('Text Field', 'formarea');
      actions.iSeeText('Text Field Component');
      actions.enterTextInField('#label', 'Text Field');
      actions.clickOnElementWithText('Save');
      actions.waitForActionToComplete(1000);
      actions.clickOnElementWithText('Create Form');
    // actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('Resources');
      actions.clickOnElementWithText(' New Resource');
      actions.checkingUrlEndsWith('/resource/create/resource');
      actions.enterTextInField('#title', 'Test Resource');
      actions.iSeeValueIn('#name', 'testResource');
      actions.iSeeValueIn('#path', 'testresource');
      actions.clickOnButton('Create Resource');
      actions.iSeeTextIn(".toast-message", 'Successfully created form!');
      actions.iSeeText('Save Resource');
      actions.clickOnElementWithText('Settings');
      actions.clickOnElementWithText('Integrations');
      actions.checkingUrlEndsWith('env/integrations/info');
      actions.clickOnElementWithText('Email Providers');
      actions.clickOnElementWithText('SendGrid Settings');
      actions.enterTextInField('#sendGridPassword', 'sendGridPassword');
      actions.clickOnElementWithText('Save Settings');
    // actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('File Storage');
      actions.clickOnElementWithText('Amazon S3 / Minio (On-Premise, Private Cloud)');
      actions.enterTextInField('#AWSAccessKeyId', 'AWSAccessKeyId');
      actions.clickOnElementWithText('Save Settings');
    // actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('Data Connections');
      actions.clickOnElementWithText('Kickbox');
      actions.enterTextInField('#kickbox-apikey', 'kickbox-apikey');
      actions.clickOnElementWithText('Save Settings');
    // actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('Settings');
      actions.iSeeText(' Live ');
      actions.iDonotSeeText('Delete Live Stage');
      actions.checkElement('//*[@id="protect"]');
      actions.clickOnElementWithText(' Save Stage');
      actions.waitForActionToComplete(2000);
      actions.checkElementIsDisabled('//*[@id="form-group-title"]/input');
      actions.clickOnElementWithText('+ New Stage');
      actions.btnDisabled(' Add Stage');
      actions.enterTextInField('#title', 'Dev');
      actions.clickOnElementWithText(' Add Stage');
      actions.waitForActionToComplete(1000);
      actions.iSeeText('Dev Project Url:');
      actions.clickOnElementWithText('Forms');
      actions.checkElementWithTextIsNotDisabled(' New Form');
      actions.iSeeText('Test Form');
      actions.clickOnElementWithText('Resources');
      actions.iSeeText('Test Resource');
      actions.clickOnElementWithText('Settings');
      actions.clickOnElementWithText('Integrations');
      actions.checkingUrlEndsWith('env/integrations/info');
      actions.clickOnElementWithText('Email Providers');
      actions.clickOnElementWithText('SendGrid Settings');
      actions.iDonotSeeText('sendGridPassword');
      actions.clickOnElementWithText('File Storage');
      actions.clickOnElementWithText('Amazon S3 / Minio (On-Premise, Private Cloud)');
      actions.iDonotSeeText('AWSAccessKeyId');
      actions.clickOnElementWithText('Data Connections');
      actions.clickOnElementWithText('Kickbox');
      actions.iDonotSeeText('kickbox-apikey');
    });
    tags('smoke').describe('',function(){
      var path = ['Dev1','Dev2','Dev3','Dev4','Dev5','Dev6','Dev7','Dev8'];
      path.forEach(function (value) {
        actions.clickOnElementWithText('+ New Stage');
        actions.enterTextInField('#title', value);
        actions.clickOnElementWithText(' Add Stage');
      // actions.clickOnClass('.toast-message');
        actions.waitForActionToComplete(1000);
        actions.checkingUrlEndsWith('/overview');
      });
      actions.iDonotSeeText('+ New Stage');
      actions.clickOnElementWithText(' Dev ');
      actions.clickOnElementWithText('Settings');
      actions.iSeeText('Dev Project Url:');
      actions.enterTextInField('#title', 'Updated Dev');
      actions.clickOnElementWithText(' Save Stage');
    // actions.clickOnClass('.toast-message');
      actions.iDonotSeeText('Dev Project Url:');
      actions.iSeeText('Updated Dev Project Url:');
      actions.clickOnElementWithText(' Updated Dev ');
      actions.clickOnElementWithText('Settings');
      actions.clickOnElementWithText('Delete Updated Dev Stage');
      actions.clickOnElementWithText(' Yes');
      actions.iDonotSeeText(' Updated Dev ');
      actions.clickOnElementWithText(' Live ');
      actions.clickOnElementWithText('Settings');
      actions.checkElement('//*[@id="protect"]');
      actions.clickOnElementWithText(' Save Stage');
      actions.waitForActionToComplete(2000);
      actions.clickOnElementWithText('Forms');
      actions.checkingUrlEndsWith('/form/');
      actions.clickOnElementWithText(' New Form');
      actions.clickOnElementWithText('API Web Form');
      actions.enterTextInField('#title','Live Form');
      actions.clickOnElementWithText('Create Form');
    // actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('Resources');
      actions.clickOnElementWithText(' New Resource');
      actions.checkingUrlEndsWith('/resource/create/resource');
      actions.enterTextInField('#title','Live Resource');
      actions.clickOnButton('Create Resource');
    // actions.clickOnClass('.toast-message');

      actions.clickOnElementWithText(' Dev1 ');
      actions.clickOnElementWithText('Forms');
      actions.iDonotSeeText('Live Form');
      actions.clickOnElementWithText('Resources');
      actions.iDonotSeeText('Live Resource');

      actions.clickOnElementWithText('+ New Stage');
      actions.enterTextInField('#title','New Dev');
      actions.clickOnElementWithText(' Add Stage');
      actions.waitForActionToComplete(1000);
      actions.checkingUrlEndsWith('/overview');
      actions.clickOnElementWithText('Forms');
      actions.iSeeText('Live Form');
      actions.clickOnElementWithText('Resources');
      actions.iSeeText('Live Resource');

      actions.clickOnElementWithText(' Live ');
      actions.clickOnElementWithText('Forms');
      actions.clickOnElementWithText('Test Form');
      actions.clickOnElementWithText(' Use');
      actions.iSeeText('Submit Form');
      actions.iSeeText('Text Field');
      actions.enterTextInField('#textField','Test Submission');
      actions.clickOnButton('Submit');
      actions.iSeeTextIn(".toast-message",'New submission added!');

      actions.clickOnElementWithText(' Dev1 ');
      actions.clickOnElementWithText('Forms');
      actions.clickOnElementWithText('Test Form');
      actions.clickOnElementWithText(' Data');
      actions.checkingUrlEndsWith('/submission');
      actions.iSeeText('{...} Export JSON');
      actions.iSeeText(' Export CSV');
      actions.iDonotSeeText('Test Submission');
    });
    tags('smoke').describe('Removing Environment',function() {
      actions.clickOnElementWithText(' Dev1 ');
      actions.clickOnElementWithText('Settings');
      actions.clickOnElementWithText('Delete Dev1 Stage');
      actions.clickOnElementWithText('No');
      actions.iSeeText(' Dev1 ');
      actions.clickOnElementWithText('Delete Dev1 Stage');
      actions.clickOnElementWithText(' Yes');
      actions.iDonotSeeText(' Dev1 ');

      actions.clickOnElementWithText(' Live ');
      actions.clickOnElementWithText('Settings');
      actions.iDonotSeeText('Delete Live Stage');
    });
  });
};
