module.exports = function (actions,tags) {
  tags('smoke').describe('Overview Page',function() {
    actions.logout();
    actions.iAmLoggedInFor('projuser2');
    actions.goToPage("#/");
    actions.projectExisting('${random-title>project3.title}', '${random-description>project3.description}');
    actions.iSeeTextIn('.project.well>h4>a', '${project3.title}');
    actions.clickOnButton('Manage');
    actions.clickOnElementWithText('Forms');
    actions.checkingUrlEndsWith('/form/');
    actions.clickOnElementWithText(' New Form');
    actions.clickOnElementWithText('API Web Form');
    actions.iSeeElement('.form-edit');
    actions.enterTextInField('#title','Test Form');
    actions.clickOnElementWithText('Create Form');
  // actions.clickOnClass('.toast-message');
    actions.clickOnElementWithText('Resources');
    actions.clickOnElementWithText(' New Resource');
    actions.iSeeElement('.form-edit');
    actions.checkingUrlEndsWith('/resource/create/resource');
    actions.enterTextInField('#title','Test Resource');
    actions.clickOnButton('Create Resource');
  // actions.clickOnClass('.toast-message');
    actions.clickOnElementWithText('Overview');
    actions.clickOnElementWithText('More...');
    actions.checkingUrlEndsWith('/form/');
    // actions.clickOnElementWithText('Test Form');
    // actions.dragTo('Text Field', 'formarea');
    // actions.iSeeText('Text Field Component');
    // actions.enterTextInField('#label', 'Text Field');
    // actions.clickOnElementWithText('Save');
    // actions.waitForActionToComplete(1000);
    // actions.clickSave('Save Form');
    // actions.clickOnClass('.toast-message');
    // actions.clickOnElementWithText('Resources');
    // actions.clickOnElementWithText('Test Resource');
    // actions.dragTo('Text Field', 'formarea');
    // actions.iSeeText('Text Field Component');
    // actions.enterTextInField('#label', 'Text Field');
    // actions.clickOnElementWithText('Save');
    // actions.waitForActionToComplete(1000);
    // actions.clickSave('Save Resource');
    // actions.clickOnClass('.toast-message');
    // actions.clickOnElementWithText('Overview');
    // actions.checkingUrlEndsWith('/overview');
    // actions.iSeeText('Test Form');
    // actions.iSeeText('Test Resource');
    // actions.clickOnElementWithText('Edit');
    // actions.iSeeText('Test Resource');
    // actions.checkingUrlEndsWith('/edit');
    // actions.clickOnElementWithText('Overview');
    // actions.checkingUrlEndsWith('/overview');
    // actions.clickOnElementWithTextIndex('Edit',1);
    // actions.iSeeText('Test Form');
    // actions.checkingUrlEndsWith('/edit');
    actions.clickOnElementWithText('Overview');
    actions.checkingUrlEndsWith('/overview');
    actions.clickOnElementWithText('Change');
    actions.checkingUrlEndsWith('/settings');
    actions.clickOnElementWithText('Overview');
    actions.checkingUrlEndsWith('/overview');
    actions.clickOnElementWithText('View Walkthrough');
    actions.checkingUrlEndsWith('/tour');
    actions.iSeeText('Welcome to Your New Project!');
    actions.clickOnElementWithText('Overview');
    actions.checkingUrlEndsWith('/overview');
    actions.iSeeText(' / 10,000');
    actions.iSeeText('You are the project ');
    actions.iSeeText('owner');
    actions.clickOnClassWithIndex('.fa.text-success',2);
    actions.iSeeText('Submission Activity');
  });
}
