module.exports = function (actions) {
  describe('User Profile Functionality',function(){
    describe('Profile navigation',function(){
      actions.logout();
      actions.iAmLoggedInFor('profileuser1');
      actions.goToPage('#/');
      actions.clickOnElement('#user-menu');
      actions.clickOnElementWithText(' Profile');
      actions.checkingUrlIamOn("#/profile/view");
      actions.iSeeText("User Profile");
      actions.iSeeValueIn("#profile-username","Username: ${profileuser1.name}");
      actions.iSeeValueIn("#profile-email","Email: ${profileuser1.email}");
      actions.clickOnElementWithText('Edit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.enterTextInField('#fullName','Test');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueIn('#fullName','Test');
      actions.enterTextInField('#name','${random-name>profileuser1.name}');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueIn('#name','${profileuser1.name}');
      actions.iSeeValueIn('#user-menu','${profileuser1.name}');
      actions.enterTextInField('#email','${random-email>profileuser1.email}');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueIn('#email','${profileuser1.email}');
      actions.enterTextInField('#password','password');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueIn('#password','password');
      actions.logout();
      actions.enterTextInField('.login-container #email', '${profileuser1.email}');
      actions.enterTextInField('.login-container #password', 'password');
      actions.clickOnElementWithText('LOG IN');
      actions.iAmLoggedIn();
      actions.logout();
    });
    // describe('Update fullname',function(){
    //   actions.logout();
    //   actions.iAmLoggedInFor('profileuser1');
    //   actions.goToPage('#/profile/edit');
    //   // actions.iSeeTextIn(".control-label","Name");
    //   actions.enterTextInField('.profile-edit-page #fullName','${random-fullName>profileuser1.fullName}');
    //   actions.clickOnElementWithText('Submit');
    //   actions.iSeeTextIn(".alert","Submission was updated.");
    //   actions.valueUpdate('profileuser1','${random}','fullName');
    //   actions.valueChanged('profileuser1');
    // });
    // describe('Update username',function(){
    //   actions.logout();
    //   actions.iAmLoggedInFor('profileuser1');
    //   actions.goToPage('#/profile/edit');
    //   // actions.iSeeText("Username");
    //   actions.enterTextInField('.profile-edit-page #name','${random-name>profileuser1.name}');
    //   actions.clickOnElementWithText('Submit');
    //   actions.iSeeTextIn(".alert","Submission was updated.");
    //   actions.valueUpdate('profileuser1','${random}','name');
    //   actions.valueChanged('profileuser1');
    // });
    // describe('Update email',function(){
    //   actions.logout();
    //   actions.iAmLoggedInFor('profileuser1');
    //   actions.goToPage('#/profile/edit');
    //   // actions.iSeeText("Email");
    //   actions.enterTextInField('.profile-edit-page #email','${random-email>profileuser1.email}');
    //   actions.clickOnElementWithText('Submit');
    //   actions.iSeeTextIn(".alert","Submission was updated.");
    //   actions.valueUpdate('profileuser1','${random}','email');
    //   actions.valueChanged('profileuser1');
    // });
    // describe('Update password',function(){
    //   actions.logout();
    //   actions.iAmLoggedInFor('profileuser1');
    //   actions.goToPage('#/profile/edit');
    //   actions.iSeeText("Password");
    //   actions.enterTextInField('.profile-edit-page #password','${random-password>profileuser1.password}');
    //   actions.clickOnElementWithText('Submit');
    //   actions.iSeeTextIn(".alert","Submission was updated.");
    //   actions.valueUpdate('profileuser1','${random}','password');
    //   actions.valueChanged('profileuser1');
    // });
    // describe('Update all profile settings',function(){
    //   actions.logout();
    //   actions.iAmLoggedInFor('profileuser1');
    //   actions.goToPage('#/profile/edit');
    //   actions.iSeeTextIn(".control-label","Name");
    //   actions.iSeeText("Username");
    //   actions.iSeeText("Email");
    //   actions.iSeeText("Password");
    //   actions.enterTextInField('.profile-edit-page #fullName','${random-fullName>profileuser1.fullName}');
    //   actions.enterTextInField('.profile-edit-page #name','${random-name>profileuser1.name}');
    //   actions.enterTextInField('.profile-edit-page #email','${random-email>profileuser1.email}');
    //   actions.enterTextInField('.profile-edit-page #password','${random-password>profileuser1.password}');
    //   actions.clickOnElementWithText('Submit');
    //   actions.iSeeTextIn(".alert","Submission was updated.");
    //   actions.valueChanged('profileuser1');
    // });
  });
};
