module.exports = function (actions,tags) {
  tags('smoke').describe('User Profile Functionality',function(){
    describe('Profile navigation',function(){
      actions.logout();
      actions.iAmLoggedInFor('projuser8');
      actions.waitForActionToComplete(2000);
      actions.goToPage('#/');
      actions.clickOnElement('#user-menu');
      actions.clickOnElementWithText(' Profile');
      actions.checkingUrlIamOn("#/profile/view");
      actions.iSeeText("User Profile");
      actions.clickOnElementWithText('Edit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',0,'Test');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueInIndex('xpath://*[contains(@class, \'form-control\')]',0,'Test');
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',1,'${random-name>profileuser1.name}');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueIn('#name','${profileuser1.name}');
      actions.enterTextInField('#email','${random-email>profileuser1.email}');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueInIndex('xpath://*[contains(@class, \'form-control\')]',2,'${profileuser1.email}');
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',3,'password');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.logout();
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',0,'${profileuser1.email}');
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',1, 'password');
      actions.clickOnElementWithText('LOG IN');
      actions.clickOnElement('#user-menu');
      actions.clickOnElementWithText(' Profile');
      actions.checkingUrlIamOn("#/profile/view");
      actions.clickOnElementWithText('Edit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.enterTextInField('#name','');
      actions.iSeeText('Username is required.');
      actions.enterTextInField('#name','${random-name>profileuser1.name}');
      actions.enterTextInField('#email','');
      actions.iSeeText('Email is required.');
      actions.enterTextInField('#email','${random-email>profileuser1.email}');
      actions.logout();
    });
  });
};
