module.exports = function (actions) {
  describe('User Profile Functionality',function(){
    describe('Profile navigation',function(){
      actions.logout();
      actions.iAmLoggedInFor('projuser8');
      actions.waitForActionToComplete(2000);
      actions.goToPage('#/');
      actions.clickOnElement('#user-menu');
      actions.clickOnElementWithText(' Profile');
      actions.checkingUrlIamOn("#/profile/view");
      actions.iSeeText("User Profile");
      actions.iSeeValueIn("#profile-username","Username: ${profileuser1.name}");
      actions.iSeeValueIn("#profile-email","Email: ${profileuser1.email}");
      actions.clickOnElementWithText('Edit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',0,'Test');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueInIndex('xpath://*[contains(@class, \'form-control\')]',0,'Test');
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',1,'${random-name>profileuser1.name}');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueInIndex('xpath://*[contains(@class, \'form-control\')]',1,'${profileuser1.name}');
      actions.iSeeValueIn('#user-menu','${profileuser1.name}');
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',2,'${random-email>profileuser1.email}');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueInIndex('xpath://*[contains(@class, \'form-control\')]',2,'${profileuser1.email}');
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',3,'password');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.iSeeValueInIndex('xpath://*[contains(@class, \'form-control\')]',3,'password');
      actions.logout();
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',0,'${profileuser1.email}');
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',1, 'password');
      actions.clickOnElementWithText('LOG IN');
      actions.clickOnElement('#user-menu');
      actions.clickOnElementWithText(' Profile');
      actions.checkingUrlIamOn("#/profile/view");
      actions.clickOnElementWithText('Edit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',1,'${empty}');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',1,'${random-name>profileuser1.name}');
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',2,'${empty}');
      actions.clickOnElementWithText('Submit');
      actions.checkingUrlIamOn("#/profile/edit");
      actions.enterTextInFieldIndex('xpath://*[contains(@class, \'form-control\')]',2,'${random-email>profileuser1.email}');
      actions.logout();
    });
  });
};
