module.exports = function (actions) {
  describe('Independent Plan Settings',function(){
    describe('Independent Plan > Environment Settings',function(){
      actions.logout();
      actions.enterTextInField('.login-container #email','admin@example.com');
      actions.enterTextInField('.login-container #password','password');
      actions.clickOnElementWithText('LOG IN');
      actions.waitForActionToComplete(2000);
      // actions.iAmLoggedInFor('profileuser2');
      // actions.goToPage('#/');
      // actions.goToPage('#/profile/payment/view');
      // actions.clickOnElementWithText('Add Credit Card');
      // actions.enterTextInField('#cardholderName','Test');
      // actions.enterTextInField('#ccNumber','4111111111111111');
      // actions.enterTextInField('#securityCode','411');
      // actions.clickOnClass('#form-group-ccExpiryMonth');
      // actions.clickOnElementWithText('01');
      // actions.clickOnClass('#form-group-ccExpiryYear');
      // actions.clickOnElementWithText('25');
      // actions.clickOnClass('#submit');
      // actions.waitForActionToComplete(50000);
      // actions.goToPage('#/');
      // actions.clickOnElementWithText('New Project');
      // actions.enterTextInField('#title','testProject');
      // actions.clickOnElementWithText(' Create Project');
      // actions.clickOnElementWithText('Trial');
      // actions.clickOnElementWithText('Upgrade');
      // actions.waitForActionToComplete(5000);
      actions.goToPage('#/project/59d3d2ad4962aa0ac03499e2/overview');
      actions.clickOnLink('Settings');
      actions.checkElementIsDisabled('//*[@id="form-group-title"]/input');
      actions.checkElementIsNotDisabled('//*[@id="name"]');
      actions.enterTextInField('#name','independent');
      actions.clickOnElementWithText(' Save Stage');
      actions.iSeeValueIn('#name','independent');
      actions.clickOnLink('Overview');
      actions.iSeeText('independent');
      actions.clickOnLink('Forms');
      actions.clickOnElementWithText('User Login');
      actions.iSeeValueIn('#form-group-path','independent');
      actions.clickOnLink('Resources');
      actions.clickOnElementWithText(' API');
      actions.iSeeValueIn('.wrap-table-cell','independent');
      actions.clickOnLink('Settings');
      actions.checkElement('//*[@id="protect"]');
      actions.iSeeElement('i.fa.fa-shield.ng-scope');
      actions.clickOnElementWithText(' Save Stage');
      actions.iSeeText('Project saved.');
      actions.clickOnLink('Forms');
      actions.checkElementWithTextIsDisabled(' New Form');
      actions.checkElementWithTextIsDisabled(' Edit');
      actions.checkElementWithTextIsDisabled(' Actions');
      actions.checkElementWithTextIsDisabled(' Access');
      actions.checkElementWithTextIsNotDisabled(' Use');
      actions.checkElementWithTextIsNotDisabled(' Embed');
      actions.clickOnElementWithText(' Data');
      actions.checkElementWithTextIsNotDisabled('{...} Export JSON');
      actions.checkElementWithTextIsNotDisabled(' Export CSV');
      actions.clickOnLink('Settings');
      actions.clickOnElementWithText('Remote Environment');
      actions.iSeeText('Upgrade your project to a team or commercial plan to enable Remote Environments.');
      actions.clickOnElementWithText('API Keys');
      actions.clickOnClass('.fa.fa-trash');
      actions.clickOnElementWithText('Add New Key');
      actions.clickOnElementWithText('CORS');
      actions.iSeeText('Upgrade your project to a paid plan to enable CORS Settings.');
      actions.clickOnElementWithText('Custom JS and CSS');
      actions.checkingUrlIamOn('http://localhost:9002/#/project/59d3d2ad4962aa0ac03499e2/env/settings/customjscss');
    });
    describe('Independent  Plan > Deployment Settings',function(){
      // actions.enterTextInField('.login-container #email','admin@example.com');
      // actions.enterTextInField('.login-container #password','password');
      // actions.clickOnElementWithText('LOG IN');
      // actions.waitForActionToComplete(2000);
      // actions.goToPage('#/project/59d3d2ad4962aa0ac03499e2/overview');
      actions.clickOnLink('Settings');
      actions.checkElement('//*[@id="protect"]');
      actions.clickOnElementWithText(' Save Stage');
      actions.clickOnElementWithText('Staging');
      actions.clickOnElementWithText('Staging');
      actions.iSeeText('Upgrade your project to Enterprise to enable deploying to stages.');
      actions.clickOnElementWithText('Create Version Tag');
      actions.iSeeText('Upgrade your project to Enterprise to enable deploying to stages.');
      actions.clickOnElementWithText('Import Template');
      actions.checkingUrlIamOn('http://localhost:9002/#/project/59d3d2ad4962aa0ac03499e2/env/staging/import');
      actions.clickOnElementWithText('Export Template');
      actions.checkingUrlIamOn('http://localhost:9002/#/project/59d3d2ad4962aa0ac03499e2/env/staging/export');
    });
    describe('Independent  Plan > Integrations Settings',function(){
      // actions.enterTextInField('.login-container #email','admin@example.com');
      // actions.enterTextInField('.login-container #password','password');
      // actions.clickOnElementWithText('LOG IN');
      // actions.waitForActionToComplete(2000);
      // actions.goToPage('#/project/59d3d2ad4962aa0ac03499e2/overview');
      actions.clickOnLink('Settings');
      actions.clickOnElementWithText('Integrations');
      actions.checkingUrlIamOn('http://localhost:9002/#/project/59d3d2ad4962aa0ac03499e2/env/integrations/info');
      actions.clickOnElementWithText('PDFs');
      actions.checkingUrlIamOn('http://localhost:9002/#/project/59d3d2ad4962aa0ac03499e2/env/pdf');
      actions.clickOnElementWithText('Email Providers');
      actions.iSeeText('SMTP Settings');
      actions.iSeeText('SendGrid Settings');
      actions.iSeeText('Mailgun Settings');
      actions.iSeeText('Custom Email Server');
      actions.clickOnElementWithText('SMTP Settings');
      actions.checkElement('//*[@id="smtpSecure"]');
      actions.enterTextInField('#smtpHost','smtpHost');
      actions.enterTextInField('#smtpPort','smtpPort');
      actions.enterTextInField('#smtpUser','smtpUser');
      actions.enterTextInField('#smtpPass','smtpPass');
      actions.clickOnElementWithText('Save Settings');
      actions.clickOnElementWithText('Forms');
      actions.clickOnElementWithText(' Actions');
      actions.clickOnElementWithText('Select an Action');
      actions.clickOnElementWithText('Email');
      actions.clickOnElementWithText(' Add Action');
      actions.clickOnClass('#transport');
      actions.iSeeText('SMTP');
      actions.clickOnLink('Settings');
      actions.clickOnElementWithText('Integrations');
      actions.clickOnElementWithText('Email Providers');
      actions.clickOnElementWithText('SendGrid Settings');
      actions.enterTextInField('#sendGridPassword','sendGridPassword');
      actions.clickOnElementWithText('Save Settings');
      actions.clickOnElementWithText('Forms');
      actions.clickOnElementWithText(' Actions');
      actions.clickOnElementWithText('Select an Action');
      actions.clickOnElementWithText('Email');
      actions.clickOnElementWithText(' Add Action');
      actions.clickOnClass('#transport');
      actions.iSeeText('SendGrid');
      actions.clickOnLink('Settings');
      actions.clickOnElementWithText('Integrations');
      actions.clickOnElementWithText('Email Providers');
      actions.clickOnElementWithText('Mailgun Settings');
      actions.enterTextInField('#mailgunAPIKey','mailgunAPIKey');
      actions.enterTextInField('#mailgunDomain','mailgunDomain');
      actions.clickOnElementWithText('Save Settings');
      actions.clickOnElementWithText('Forms');
      actions.clickOnElementWithText(' Actions');
      actions.clickOnElementWithText('Select an Action');
      actions.clickOnElementWithText('Email');
      actions.clickOnElementWithText(' Add Action');
      actions.clickOnClass('#transport');
      actions.iSeeText('Mailgun');
      actions.clickOnLink('Settings');
      actions.clickOnElementWithText('Integrations');
      actions.clickOnElementWithText('Email Providers');
      actions.clickOnElementWithText('Custom Email Server');
      actions.enterTextInField('#customUrl','customUrl');
      actions.enterTextInField('#customPassword','customPassword');
      actions.clickOnElementWithText('Save Settings');
      actions.clickOnElementWithText('Forms');
      actions.clickOnElementWithText(' Actions');
      actions.clickOnElementWithText('Select an Action');
      actions.clickOnElementWithText('Email');
      actions.clickOnElementWithText(' Add Action');
      actions.clickOnClass('#transport');
      actions.iSeeText('Custom');
      actions.clickOnLink('Settings');
      actions.clickOnElementWithText('Integrations');
      actions.clickOnElementWithText('File Storage');
      actions.iSeeText('Upgrade your project to a paid plan to access file storage settings.');
      actions.clickOnElementWithText('Data Connections');
      actions.clickOnElementWithText('OAuth');
    });
  });
};
