module.exports = function (actions) {
  describe('Creating/Deleting/Editing a team',function(){
    describe('Create Teams Basic',function() {
      actions.logout();
      actions.enterTextInField('.login-container #email', 'automatedTeam@tests');
      actions.enterTextInField('.login-container #password', 'password');
      actions.clickOnElementWithText('LOG IN');
      actions.iAmLoggedIn();
      actions.clickOnElementWithText('New Project');
      actions.enterTextInField('#title', 'teamsBasicProject');
      actions.clickOnElementWithText(' Create Project');
      actions.enableAngular(true);
      actions.clickOnElementWithText('Trial');
      actions.upgradeToPlan("Basic");
      actions.clickOnElementWithText(' Confirm Billing Change');
      actions.waitForActionToComplete(2000);
      actions.iSeeTextIn("a.project-plan.label-info", "Basic");
      actions.clickOnElementWithText(" Teams");
      actions.iSeeText("Upgrade your project to Team Pro or above to enable teams.");
      actions.clickOnClass('.fa.fa-cog');
      actions.clickOnElementWithText('Delete teamsBasicProject Project');
      actions.clickOnElementWithText(' Yes');
      actions.iDonotSeeText('teamsBasicProject');
    });
    describe('Create Teams Independent',function() {
      actions.logout();
      actions.enterTextInField('.login-container #email', 'automatedTeam@tests');
      actions.enterTextInField('.login-container #password', 'password');
      actions.clickOnElementWithText('LOG IN');
      actions.iAmLoggedIn();
      actions.clickOnElementWithText('New Project');
      actions.enterTextInField('#title', 'teamsIndependentProject');
      actions.clickOnElementWithText(' Create Project');
      actions.enableAngular(true);
      actions.clickOnElementWithText('Trial');
      actions.upgradeToPlan("Independent");
      actions.clickOnElementWithText(' Confirm Billing Change');
      actions.waitForActionToComplete(2000);
      actions.iSeeTextIn("a.project-plan.label-warning", "Independent");
      actions.clickOnElementWithText(" Teams");
      actions.iSeeText("Upgrade your project to Team Pro or above to enable teams.");
      actions.clickOnClass('.fa.fa-cog');
      actions.clickOnElementWithText('Delete teamsIndependentProject Project');
      actions.clickOnElementWithText(' Yes');
      actions.iDonotSeeText('teamsIndependentProject');
    });
    describe('Create Teams Team Pro',function() {
      actions.logout();
      actions.enterTextInField('.login-container #email', 'automatedTeam@tests');
      actions.enterTextInField('.login-container #password', 'password');
      actions.clickOnElementWithText('LOG IN');
      actions.iAmLoggedIn();
      actions.clickOnElementWithText('New Project');
      actions.enterTextInField('#title', 'teamsTeamProProject');
      actions.clickOnElementWithText(' Create Project');
      actions.enableAngular(true);
      actions.clickOnElementWithText('Trial');
      actions.upgradeToPlan("Team Pro");
      actions.clickOnElementWithText(' Confirm Billing Change');
      actions.waitForActionToComplete(2000);
      actions.iSeeTextIn("a.project-plan.label-success","Team Pro");
      actions.clickOnElementWithText(" Teams");
      actions.clickOnClass("span.btn.btn-default.form-control.ui-select-toggle");
      actions.iDonotSeeText("automatedTeam");
      actions.clickOnElementWithText("Create a New Team");
      actions.enterTextInField("#name","automatedTeam");
      actions.clickOnElementWithText("Submit");
      actions.clickOnClass('.fa.fa-home');
      actions.clickOnElementWithText('teamsTeamProProject');
      actions.waitForActionToComplete(2000);
      actions.clickOnElementWithText(" Teams");
      actions.clickOnClass("span.btn.btn-default.form-control.ui-select-toggle");
      actions.iSeeText("automatedTeam");
      actions.clickOnClass('.fa.fa-cog');
      actions.clickOnElementWithText('Delete teamsTeamProProject Project');
      actions.clickOnElementWithText(' Yes');
      actions.iDonotSeeText('teamsTeamProProject');
    });
  });
};
