module.exports = function (actions) {
  describe('Creating/Deleting/Editing a team',function(){
    // describe('Create Teams Basic',function() {
    //   actions.logout();
    //   actions.enterTextInField('.login-container #email', 'automatedTeam@tests');
    //   actions.enterTextInField('.login-container #password', 'password');
    //   actions.clickOnElementWithText('LOG IN');
    //   actions.iAmLoggedIn();
    //   // actions.logout();
    //   // actions.iAmLoggedInFor('profileuser1');
    //   // actions.iAmLoggedIn();
    //   // actions.goToPage('#/profile/payment/view');
    //   // actions.clickOnElementWithText('Add Credit Card');
    //   // actions.enterTextInField('#cardholderName','Test');
    //   // actions.enterTextInField('#ccNumber','4111111111111111');
    //   // actions.enterTextInField('#securityCode','411');
    //   // actions.clickOnClass('#form-group-ccExpiryMonth');
    //   // actions.clickOnElementWithText('01');
    //   // actions.clickOnClass('#form-group-ccExpiryYear');
    //   // actions.clickOnElementWithText('25');
    //   // actions.clickOnClass('#submit');
    //   // actions.goToPage('#/');
    //   actions.clickOnElementWithText('New Project');
    //   actions.enterTextInField('#title', 'teamsBasicProject');
    //   actions.clickOnElementWithText(' Create Project');
    //   actions.enableAngular(true);
    //   actions.clickOnElementWithText('Trial');
    //   actions.upgradeToPlan("Basic");
    //   actions.clickOnElementWithText(' Confirm Billing Change');
    //   actions.iSeeTextIn("a.project-plan.label-info", "Basic");
    //   actions.clickOnElementWithText(" Teams");
    //   actions.iSeeText("Upgrade your project to Team Pro or above to enable teams.");
    //   actions.clickOnClass('.fa.fa-cog');
    //   actions.clickOnElementWithText('Delete teamsBasicProject Project');
    //   actions.clickOnElementWithText(' Yes');
    //   actions.iDonotSeeText('teamsBasicProject');
    // });
    // describe('Create Teams Independent',function() {
    //   actions.logout();
    //   actions.enterTextInField('.login-container #email', 'automatedTeam@tests');
    //   actions.enterTextInField('.login-container #password', 'password');
    //   actions.clickOnElementWithText('LOG IN');
    //   actions.iAmLoggedIn();
    //   // actions.logout();
    //   // actions.iAmLoggedInFor('profileuser1');
    //   // actions.iAmLoggedIn();
    //   // actions.goToPage('#/profile/payment/view');
    //   // actions.clickOnElementWithText('Add Credit Card');
    //   // actions.enterTextInField('#cardholderName','Test');
    //   // actions.enterTextInField('#ccNumber','4111111111111111');
    //   // actions.enterTextInField('#securityCode','411');
    //   // actions.clickOnClass('#form-group-ccExpiryMonth');
    //   // actions.clickOnElementWithText('01');
    //   // actions.clickOnClass('#form-group-ccExpiryYear');
    //   // actions.clickOnElementWithText('25');
    //   // actions.clickOnClass('#submit');
    //   // actions.goToPage('#/');
    //   actions.clickOnElementWithText('New Project');
    //   actions.enterTextInField('#title', 'teamsIndependentProject');
    //   actions.clickOnElementWithText(' Create Project');
    //   actions.enableAngular(true);
    //   actions.clickOnElementWithText('Trial');
    //   actions.upgradeToPlan("Independent");
    //   actions.clickOnElementWithText(' Confirm Billing Change');
    //   actions.iSeeTextIn("a.project-plan.label-warning", "Independent");
    //   actions.clickOnElementWithText(" Teams");
    //   actions.iSeeText("Upgrade your project to Team Pro or above to enable teams.");
    //   actions.clickOnClass('.fa.fa-cog');
    //   actions.clickOnElementWithText('Delete teamsIndependentProject Project');
    //   actions.clickOnElementWithText(' Yes');
    //   actions.iDonotSeeText('teamsIndependentProject');
    // });
    describe('Create Teams Team Pro',function() {
      actions.logout();
      actions.enterTextInField('.login-container #email', 'admin@example.com');
      actions.enterTextInField('.login-container #password', 'password');
      actions.clickOnElementWithText('LOG IN');
      actions.iAmLoggedIn();
      // actions.logout();
      // actions.iAmLoggedInFor('profileuser1');
      // actions.iAmLoggedIn();
      // actions.goToPage('#/profile/payment/view');
      // actions.clickOnElementWithText('Add Credit Card');
      // actions.enterTextInField('#cardholderName','Test');
      // actions.enterTextInField('#ccNumber','4111111111111111');
      // actions.enterTextInField('#securityCode','411');
      // actions.clickOnClass('#form-group-ccExpiryMonth');
      // actions.clickOnElementWithText('01');
      // actions.clickOnClass('#form-group-ccExpiryYear');
      // actions.clickOnElementWithText('25');
      // actions.clickOnClass('#submit');
      // actions.goToPage('#/');
      actions.clickOnElementWithText('New Project');
      actions.enterTextInField('#title', 'teamsTeamProProject');
      actions.clickOnElementWithText(' Create Project');
      actions.clickOnElementWithText('Trial');
      actions.upgradeToPlan("Team Pro");
      actions.clickOnElementWithText(' Confirm Billing Change');
      actions.iSeeTextIn("a.project-plan.label-success","Team Pro");
      actions.clickOnElementWithText(" Teams");
      actions.clickOnClass("span.btn.btn-default.form-control.ui-select-toggle");
      actions.iDonotSeeText("Beta Team");
      actions.clickOnElementWithText("Create a New Team");
      actions.btnDisabled("Submit");
      actions.enterTextInField("#name","Beta Team");
      actions.clickOnElementWithText("Submit");
      actions.iSeeText('Beta Team');
      actions.iSeeText("adminAutomated");
      actions.iSeeText("OWNER");
      actions.clickOnClass('.fa.fa-home');
      actions.iSeeText('Beta Team');
      actions.clickOnElementWithText('Beta Team');
      actions.clickOnClass('i.caret.pull-right');
      actions.enterTextInField('input','testTeam1');
      actions.clickOnElementWithText('testTeam1');
      actions.clickOnClass('i.caret.pull-right');
      actions.enterTextInField('input','testTeam2');
      actions.clickOnElementWithText('testTeam2');
      actions.clickOnElement('xpath://*[@id="main-wrapper"]/div/div/div/div[2]/div[2]/ul/li[2]/div[1]/span/span/i');
      actions.clickOnElementWithText('Make team admin');
      // actions.clickOnElement('xpath://*[@id="main-wrapper"]/div/div/div/div[2]/div[2]/ul/li[3]/div[1]/span/span/i');
      // actions.waitForActionToComplete(3000);
      // actions.clickOnElementWithText('Remove from team');
      // actions.clickOnClass('i.caret.pull-right');
      // actions.enterTextInField('input','testTeam2');
      // actions.clickOnElementWithText('testTeam2');
      actions.clickOnClass('.fa.fa-home');
      actions.clickOnElementWithText("Beta Team");
      actions.clickOnElementWithTextIndex("Projects",1);
      actions.iSeeText("Team is not assigned to any project. Visit the project team page to assign.");
      actions.clickOnClass('.fa.fa-home');
      actions.clickOnElementWithText('teamsTeamProProject');
      actions.waitForActionToComplete(3000);
      actions.clickOnElementWithText(" Teams");
      actions.clickOnClass("span.btn.btn-default.form-control.ui-select-toggle");
      actions.iSeeText("Beta Team");
      actions.clickOnElementWithText("Beta Team");
      actions.clickOnElementWithText("Beta Team");
      actions.clickOnClass('.fa.fa-home');
      actions.iSeeText("Beta Team");
      actions.clickOnElementWithText("Delete Team");
      actions.clickOnElementWithText("Yes");
      actions.clickOnElementWithText('teamsTeamProProject');
      actions.waitForActionToComplete(3000);
      actions.clickOnElementWithText(" Teams");
      actions.clickOnClass("span.btn.btn-default.form-control.ui-select-toggle");
      actions.iDonotSeeText("Beta Team");
      actions.waitForActionToComplete(3000);
      actions.clickOnClass('.fa.fa-cog');
      actions.clickOnElementWithText('Delete teamsTeamProProject Project');
      actions.clickOnElementWithText(' Yes');
      actions.iDonotSeeText('teamsTeamProProject');
    });
    describe('Assigning Team To Project - As Team Owner',function(){
      actions.logout();
      actions.enterTextInField('.login-container #email', 'admin@example.com');
      actions.enterTextInField('.login-container #password', 'password');
      actions.clickOnElementWithText('LOG IN');
      actions.iAmLoggedIn();
      actions.clickOnElementWithText(' Create Team');
      actions.btnDisabled("Submit");
      actions.enterTextInField("#name","Beta Team");
      actions.clickOnElementWithText("Submit");
      actions.clickOnElementWithText('New Project');
      actions.enterTextInField('#title', 'teamsTeamProProject');
      actions.clickOnElementWithText(' Create Project');
      actions.clickOnElementWithText('Trial');
      actions.upgradeToPlan("Team Pro");
      actions.clickOnElementWithText(' Confirm Billing Change');
    });
  });
};
