module.exports = function (actions,tags) {
  describe('Versioning ',function(){
    describe('Trial Plan',function(){
      describe('Test versioning for environments moving up and rolling back',function(){
        actions.logout();
        actions.iAmLoggedInFor('profileuser2');
        actions.goToPage('#/');
        actions.projectExisting('testVersioningProject', 'This is a test project');
        actions.clickOnElementWithText('testVersioningProject');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnLink('Create Version');
        actions.checkingUrlEndsWith('/env/staging/create');
        actions.enterTextInField('#tag', '0.0.1');
        actions.enterTextInField('#description','Description');
        actions.clickOnElementWithText(' Create version');
      // actions.clickOnClass('.toast-message');
        actions.iSeeTextIn('.badge', '0.0.1');
        actions.iSeeText('0.0.1');
        actions.clickOnClass('input');
        actions.clickOnElementWithText ('Deploy');
        actions.clickOnElementWithText('+ New Stage');
        actions.enterTextInField('#title', 'Dev');
        actions.clickOnElementWithText(' Add Stage');
      // actions.clickOnClass('.toast-message');
        actions.checkingUrlEndsWith('/overview');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnClass('input');
        actions.clickOnElementWithText ('Deploy');
        actions.clickOnElementWithText (' Deploy version to Dev');
      // actions.clickOnClass('.toast-message');
      });
      //   describe('',function(){
      //   actions.clickOnElementWithText(' Dev ');
      //   actions.clickOnLink('Settings');
      //   actions.clickOnLink('Stage Versions');
      //   actions.clickOnLink('Create Version');
      //   actions.checkingUrlEndsWith('/env/staging/create');
      //   actions.enterTextInField('#tag', '0.0.3');
      //   actions.enterTextInField('#description','Description');
      //   actions.clickOnElementWithText(' Create version');
      // // actions.clickOnClass('.toast-message');
      //   actions.clickOnElementWithText(' Live ');
      //   actions.clickOnLink('Settings');
      //   actions.clickOnLink('Stage Versions');
      //   actions.iSeeText('Select Version Tag');
      //   actions.clickOnClass('select.form-control');
      //   actions.clickOnElementWithTextIndex('0.0.3',1);
      //   actions.clickOnElementWithText(' Deploy version to Live');
      // // actions.clickOnClass('.toast-message');
      //   actions.iSeeTextIn('.badge', '0.0.3');
      //   actions.iSeeText('Select Version ');
      //   actions.clickOnClass('select.form-control');
      //   actions.clickOnElementWithText('0.0.1');
      //   actions.clickOnElementWithText(' Deploy version to Live');
      // // actions.clickOnClass('.toast-message');
      //   actions.iSeeTextIn('.badge', '0.0.3');
      //   actions.clickOnLink('Staging');
      //   actions.selectComponentCount('.tags', 3);
      //   actions.selectComponentOption('.tags', '0.0.1');
      //   actions.clickOnElementWithText('Deploy version to Live');
      //   actions.waitForActionToComplete(2000);
      //   actions.iSeeTextIn('.badge', '0.0.1');
      //   actions.clickOnLink('Staging');
      //   actions.selectComponentCount('.tags', 3);
      //   actions.clickOnElementWithText('+ New Stage');
      //   actions.enterTextInField('#title', 'Test');
      //   actions.waitForActionToComplete(2000);
      //   actions.clickOnElementWithText(' Add Stage');
      //   actions.waitForActionToComplete(2000);
      //   actions.clickOnLink('Settings');
      //   actions.waitForActionToComplete(2000);
      //   actions.clickOnLink('Staging');
      //   actions.waitForActionToComplete(2000);
      //   actions.selectComponentOption('.tags', '0.0.1');
      //   actions.clickOnElementWithText('Deploy version tag to Test');
      //   actions.waitForActionToComplete(2000);
      //   actions.iSeeTextIn('.active .environment-tab .badge', '0.0.1');
      //   actions.waitForActionToComplete(2000);
      // });
      // describe('Versioning - Forms / Resources',function(){
      //   actions.clickOnElementWithText('Forms');
      //   actions.clickOnClass('.glyphicon.glyphicon-cloud-download');
      //   actions.enterTextInField('#embedURL','https://struntwrmesxmts.form.io/specialcomponent');
      //   actions.clickOnClass('.form-group.pull-right input');
      //   actions.enterTextInField('#title','Dev Form .2');
      //   actions.clickOnElementWithText('Create Form');
      // // actions.clickOnClass('.toast-message');
      //   actions.clickOnLink('Resources');
      //   actions.clickOnElementWithText(' New Resource');
      //   actions.enterTextInField('#title','Dev Resource .2');
      //   actions.clickOnElementWithText('Create Resource');
      // // actions.clickOnClass('.toast-message');
      //   actions.clickOnLink('Settings');
      //   actions.clickOnLink('Stage Version');
      //   actions.clickOnClass('input');
      //   actions.clickOnLink('Create');
      //   actions.enterTextInField('#tag', '0.0.2');
      //   actions.clickOnElementWithText(' Create version');
      // // actions.clickOnClass('.toast-message');
      //   actions.clickOnElementWithText(' Live ');
      //   actions.clickOnLink('Settings');
      //   actions.clickOnLink('Stage Version');
      //   actions.clickOnClass('input', '0.0.2');
      //   actions.clickOnElementWithText ('Deploy');
      //   actions.clickOnElementWithText(' Deploy version to Live');
      // // actions.clickOnClass('.toast-message');
      //   actions.clickOnElementWithText('Forms');
      //   actions.clickOnElementWithText('Dev Form .2');
      //   actions.iSeeText('Email ');
      //   actions.iSeeText('Currenct ');
      //   actions.iSeeText('Survey ');
      //   actions.clickOnLink('Resources');
      //   actions.iSeeText('Dev Resource .2');
      // });
      tags('smoke').describe('Versioning  - Form Import / Access settings',function(){
        actions.clickOnElementWithText(' Dev ');
        actions.clickOnLink('Forms');
        actions.clickOnClass('.glyphicon.glyphicon-cloud-download');
        actions.enterTextInField('#embedURL','https://basiccomponenttest.form.io/basiccomponents');
        actions.clickOnClass('.form-group.pull-right input');
        actions.enterTextInField('#title','Dev Form .3');
        actions.clickOnElementWithText('Create Form');
        actions.iSeeElement('.form-edit');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText(' Access');
        actions.clickOnClassWithIndex('.ui-select-search',1);
        actions.clickOnElementWithText('Anonymous');
        actions.clickOnClassWithIndex('.ui-select-search',3);
        actions.clickOnElementWithText('Administrator');
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',7);
        actions.clickOnElementWithTextIndex('Administrator',1);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',2);
        actions.clickOnElementWithText('Authenticated');
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',5);
        actions.clickOnElementWithTextIndex('Authenticated',1);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.close.ui-select-match-close',5);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.close.ui-select-match-close',5);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',11);
        actions.clickOnElementWithTextIndex('Anonymous',2);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',13);
        actions.clickOnElementWithTextIndex('Anonymous',3);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',14);
        actions.clickOnElementWithText('Select URL (selectUrl)');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Access');
        actions.clickOnClassWithIndex('.close.ui-select-match-close',2);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.close.ui-select-match-close',2);
      // actions.clickOnClass('.toast-message');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnLink('Create Version');
        actions.enterTextInField('#tag', '0.0.4');
        actions.clickOnElementWithText(' Create version');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText(' Live ');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnClass('input', '0.0.4');
       actions.clickOnElementWithText ('Deploy');
        actions.clickOnElementWithText(' Deploy version to Live');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Forms');
        actions.clickOnElementWithText('Dev Form .3');
        actions.clickOnElementWithText(' Access');
        actions.iSeeTextCount('Anonymous',4);
        actions.iSeeTextCount('Authenticated',2);
        actions.iSeeTextCount('Administrator',2);
        actions.iSeeText('Select URL (selectUrl)');
        actions.clickOnElementWithText('Access');
        actions.iSeeTextCount('Administrator',5);
        actions.clickOnElementWithText(' Dev ');
        actions.clickOnElementWithText('Access');
        actions.clickOnElementWithText(' New Role');
        actions.enterTextInField('#title','Test Versioning Role');
        actions.clickOnElementWithText('Create Role');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Forms');
        actions.clickOnElementWithText('Dev Form .3');
        actions.clickOnElementWithText(' Access');
        actions.clickOnClassWithIndex('.ui-select-search',0);
        actions.clickOnElementWithText('Test Versioning Role');
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',4);
        actions.clickOnElementWithTextIndex('Test Versioning Role',1);
      // actions.clickOnClass('.toast-message');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnLink('Create Version');
        actions.enterTextInField('#tag', '0.0.5');
        actions.clickOnElementWithText(' Create version');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText(' Live ');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnClass('input', '0.0.5');
       actions.clickOnElementWithText ('Deploy');
        actions.clickOnElementWithText(' Deploy version to Live');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Forms');
        actions.clickOnElementWithText('Dev Form .3');
        actions.clickOnElementWithText(' Access');
        actions.iSeeTextCount('Test Versioning Role',3);
        //
       //
      //   actions.clickOnElementWithText(' New Form');
      //   actions.clickOnElementWithText('API Web Form');
      //   actions.enterTextInField('#title','Dev Form .2');
      //   actions.clickOnElementWithText('Create Form');
      //   actions.clickOnLink('Resources');
      //   actions.clickOnElementWithText(' New Resource');
      //   actions.enterTextInField('#title','Dev Resource .2');
      //   actions.clickOnElementWithText('Create Resource');
      //   actions.clickOnLink('Settings');
      //   actions.clickOnLink('Stage Versions');
      //   actions.clickOnLink('Create Version');
      //   actions.enterTextInField('#tag', '0.0.2');
      //   actions.clickOnElementWithText('Create version');
      //   actions.waitForActionToComplete(2000);
      //   actions.clickOnElementWithText(' Live ');
      //   actions.clickOnLink('Settings');
      //   actions.clickOnLink('Stage Versions');
      //   actions.selectComponentOption('.tags', '0.0.2');
       //  actions.clickOnElementWithText ('Deploy');
      //   actions.clickOnElementWithText('Deploy version to Live');
      //   actions.clickOnLink('Forms');
      //   actions.iSeeText('Dev Form .2');
      //   actions.clickOnLink('Resources');
      //   actions.iSeeText('Dev Resource .2');
      });
      tags('smoke').describe('Versioning - Actions ',function(){
           actions.clickOnElementWithText(' Dev ');
        actions.clickOnElementWithText('Settings');
        actions.clickOnElementWithText('Integrations');
        actions.clickOnElementWithText('Data Connections');
        actions.clickOnElementWithText('Hubspot');
        actions.enterTextInField('#apikey','1234');
        actions.clickOnElementWithText('Save Settings');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('SQL Connector');
        actions.enterTextInField('#connectorHost','connectorHost');
        actions.clickOnElementWithText('Select the SQL Type');
        actions.clickOnElementWithText('MySQL');
        actions.enterTextInField('#connectorUser','connectorUser');
        actions.enterTextInField('#connectorPassword','connectorPassword');
        actions.clickOnElementWithText('Save Settings');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Authentication');
        actions.clickOnElementWithText('OAuth');
        actions.clickOnElementWithText('GitHub');
        actions.enterTextInField('#githubClientId','githubClientId');
        actions.enterTextInField('#githubClientSecret','githubClientSecret');
        actions.clickOnElementWithText('Save Settings');
      // actions.clickOnClass('.toast-message');
        actions.clickOnLink('Forms');
        actions.checkingUrlEndsWith('/form/');
        actions.clickOnElementWithText(' New Form');
        actions.clickOnElementWithText('API Web Form');
        actions.enterTextInField('#title','Version Action Test 1');
        actions.dragTo('Button', 'formarea');
        actions.enterTextInField('#label', 'TestOAuth');
        actions.selectOptionWithID('action','OAuth');
        actions.clickOnElementWithText('Save');
        actions.waitForActionToComplete(1000);
        actions.dragTo('Text Field', 'formarea');
        actions.iSeeText('Text Field Component');
        actions.enterTextInField('#label', 'Username');
        actions.clickOnElementWithText('Save');
        actions.waitForActionToComplete(1000);
        actions.dragTo('Password', 'formarea');
        actions.clickOnElementWithText('Save');
        actions.waitForActionToComplete(1000);
        actions.clickOnElementWithText('Create Form');
        actions.iSeeElement('.form-edit');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText(' Actions');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Email');
        actions.clickOnElementWithText(' Add Action');
        actions.enterTextInField('#emails','test@test.com');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Email');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Webhook (Premium)');
        actions.clickOnElementWithText(' Add Action');
      // actions.clickOnClass('.toast-message');
        actions.enterTextInField('#url','www.test.com');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Webhook (Premium)');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Role Assignment');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElementWithText('Select the type of resource to perform role manipulation.');
        actions.clickOnElementWithText('Existing Resource');
        actions.clickOnElementWithText('Select whether this Action will Add or Remove the contained Role.');
        actions.clickOnElementWithText('Add Role');
        actions.clickOnElementWithText('Select the Role that this action will Add or Remove.');
        actions.clickOnElementWithText('Administrator');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Role Assignment');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Reset Password');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElement('xpath://*[@id="resources"]/div[1]/input');
        actions.clickOnElementWithText('User');
        actions.clickOnElementWithText('Select the username field');
        actions.clickOnElementWithText('Submit');
        actions.clickOnElementWithText('Select the password field');
        actions.clickOnElementWithTextIndex('Submit',1);
        actions.enterTextInField('#url','www.test.com');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Reset Password');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Login');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElement('xpath://*[@id="resources"]/div[1]/input');
        actions.clickOnElementWithText('User');
        actions.clickOnElementWithText('Select the username field');
        actions.clickOnElementWithText('Submit');
        actions.clickOnElementWithText('Select the password field');
        actions.clickOnElementWithTextIndex('Submit',1);
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Login');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Office 365 Contacts (Premium)');
        actions.clickOnElementWithText(' Add Action');
      // actions.clickOnClass('.toast-message');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Office 365 Contacts (Premium)');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Office 365 Calendar (Premium)');
        actions.clickOnElementWithText(' Add Action');
      // actions.clickOnClass('.toast-message');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Office 365 Calendar (Premium)');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Hubspot Contact (Premium)');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        // actions.iSeeText('Hubspot Contact (Premium)');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('OAuth (Premium)');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElementWithText('Select the OAuth Provider');
        actions.clickOnElementWithText('GitHub');
        actions.clickOnElementWithText('Select the action to perform');
        actions.clickOnElementWithText('Remote Authentication');
        actions.clickOnElementWithText('Select the button that triggers OAuth sign-in');
        actions.clickOnElementWithText('TestOAuth');
        actions.clickOnClassWithIndex('.caret.pull-right',3);
        actions.clickOnElementWithText('Administrator');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('OAuth (Premium)');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('LDAP Login (Premium)');
        actions.clickOnElementWithText(' Add Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Select which field is the username field');
        actions.clickOnElementWithText('Username');
        actions.clickOnElementWithText('Select which field is the password field');
        actions.clickOnElementWithText('Password');
        actions.clickOnClassWithIndex('.caret.pull-right',2);
        actions.clickOnElementWithText('Administrator');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('LDAP Login (Premium)');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Google Sheets (Premium)');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        // actions.iSeeText('Google Sheets (Premium)');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('SQL Connector (Premium)');
        actions.clickOnElementWithText(' Add Action');
      // actions.clickOnClass('.toast-message');
        actions.enterTextInField('#table','table');
        actions.enterTextInField('#primary','primary');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Jira (Premium)');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Group Assignment (Premium)');
        actions.clickOnElementWithText(' Add Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Select the Group Resource field');
        actions.clickOnElementWithText('Username');
        actions.clickOnElementWithText('self');
        actions.clickOnElementWithText('Password');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Moxtra Login');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElementWithText('Select the resource we should login against.');
        actions.clickOnElementWithText('Dev Resource .2');
        actions.clickOnElementWithText('Select the first name field');
        actions.clickOnElementWithText('Submit');
        actions.clickOnElementWithText('Select the last name field');
        actions.clickOnElementWithTextIndex('Submit',1);
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Moxtra Message');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Moxtra Todo');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Twilio SMS (Premium)');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Version');
        actions.clickOnLink('Create Version');
        actions.checkingUrlEndsWith('/env/staging/create');
        actions.enterTextInField('#tag', '0.0.6');
        actions.clickOnElementWithText(' Create version');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText(' Live ');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Version');
        actions.clickOnClass('input', '0.0.6');
        actions.clickOnElementWithText ('Deploy');
        actions.clickOnElementWithText(' Deploy version to Live');
      // actions.clickOnClass('.toast-message');
        actions.iSeeTextIn('.badge', '0.0.6');
        actions.clickOnElementWithText('Forms');
        actions.clickOnElementWithText('Version Action Test 1');
        actions.clickOnElementWithText(' Actions');
        actions.clickOnElementWithText('Group Assignment (Premium)');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Username');
        actions.iSeeText('Password');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('LDAP Login (Premium)');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Username');
        actions.iSeeText('Password');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Login');
        actions.iSeeText('User');
        actions.iSeeTextCount('Submit',2);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Role Assignment');
        actions.iSeeText('Existing Resource');
        actions.iSeeText('Add Role');
        actions.iSeeText('Administrator');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Email');
      // actions.clickOnClass('.toast-message');
        actions.iSeeValueIn('#emails','test@test.com');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Webhook (Premium)');
      // actions.clickOnClass('.toast-message');
        actions.iSeeValueIn('#url','www.test.com');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Reset Password');
        actions.iSeeText('User');
        actions.iSeeTextCount('Submit',2);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Office 365 Contacts (Premium)');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Application Certificate');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('2');
        actions.clickOnElementWithText('Office 365 Calendar (Premium)');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Application Certificate');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('2');
        actions.clickOnElementWithText('Moxtra Login');
        actions.iSeeText('Dev Resource .2');
        actions.iSeeTextCount('Submit',2);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
      });
    })
    tags('smoke').describe('Enterprise Plan',function(){
      describe('Test versioning for environments moving up and rolling back',function() {
        actions.logout();
        actions.iAmLoggedInFor('profileuser2');
        actions.goToPage('#/');
        actions.clickOnClass('#user-menu');
        actions.clickOnElementWithText(' Payment Info');
        actions.checkingUrlEndsWith('#/profile/payment/view');
        actions.clickOnElementWithText('Add Credit Card');
        actions.enterTextInField('#cardholderName','Test');
        actions.enterTextInField('#ccNumber','4111111111111111');
        actions.enterTextInField('#securityCode','411');
        actions.clickOnClass('#form-group-ccExpiryMonth');
        actions.clickOnElementWithText('01');
        actions.clickOnClass('#form-group-ccExpiryYear');
        actions.clickOnElementWithText('25');
        actions.clickOnClass('#submit');
        actions.waitForActionToComplete(2000);
        actions.goToPage('#/');
        actions.clickOnElementWithText('New Project');
        actions.enterTextInField('#title','enterpriseVersioningProject');
        actions.clickOnElementWithText(' Create Project');
        actions.clickOnElementWithText('Trial');
        actions.upgradeToPlan("Enterprise");
        actions.clickOnButton(' Confirm Billing Change');
        actions.waitForActionToComplete(2000);
        actions.iSeeTextIn("a.project-plan.label-commercial","Enterprise");
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnLink('Create Version');
        actions.checkingUrlEndsWith('/env/staging/create');
        actions.enterTextInField('#tag', '0.0.1');
        actions.clickOnElementWithText(' Create version');
      // actions.clickOnClass('.toast-message');
        actions.iSeeTextIn('.badge', '0.0.1');
        actions.clickOnElementWithText('+ New Stage');
        actions.enterTextInField('#title', 'Dev');
        actions.clickOnElementWithText(' Add Stage');
      // actions.clickOnClass('.toast-message');
        actions.waitForActionToComplete(1000);
        actions.checkingUrlEndsWith('/overview');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnClass('input');
        actions.clickOnElementWithText ('Deploy');
        actions.clickOnElementWithText(' Deploy version to Dev');
        // actions.clickOnClass('.toast-message');
        // actions.iSeeTextIn('.badge', '0.0.1');
        // actions.clickOnElementWithText(' Dev ');
        // actions.clickOnLink('Settings');
        // actions.clickOnLink('Stage Versions');
        // actions.clickOnLink('Create Version');
        // actions.checkingUrlEndsWith('/env/staging/create');
        // actions.enterTextInField('#tag', '0.0.3');
        // actions.clickOnElementWithText(' Create version');
        // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText(' Live ');
        // actions.clickOnLink('Settings');
        // actions.clickOnLink('Stage Versions');
        // actions.clickOnClass('input', '0.0.3');
        // actions.clickOnElementWithText ('Deploy');
        // actions.clickOnElementWithText(' Deploy version to Live');
        // actions.clickOnClass('.toast-message');
        // actions.iSeeTextIn('.badge', '0.0.3');
      });
      describe('Versioning - Forms / Resources',function(){
        actions.clickOnElementWithText('Forms');
        actions.clickOnClass('.glyphicon.glyphicon-cloud-download');
        actions.enterTextInField('#embedURL','https://struntwrmesxmts.form.io/specialcomponent');
        actions.clickOnClass('.form-group.pull-right input');
        actions.enterTextInField('#title','Dev Form .2');
        actions.clickOnElementWithText('Create Form');
      // actions.clickOnClass('.toast-message');
        actions.clickOnLink('Resources');
        actions.clickOnElementWithText(' New Resource');
        actions.iSeeElement('.form-edit');
        actions.enterTextInField('#title','Dev Resource .2');
        actions.clickOnElementWithText('Create Resource');
      // actions.clickOnClass('.toast-message');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Version');
        actions.clickOnLink('Create Version');
        actions.enterTextInField('#tag', '0.0.2');
        actions.clickOnElementWithText(' Create version');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText(' Live ');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnClass('input');
        actions.clickOnLink('Deploy');
        actions.selectComponentOption('.tags', '0.0.2');
        actions.clickOnElementWithText(' Deploy version to Live');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Forms');
        actions.clickOnElementWithText('Dev Form .2');
        actions.iSeeText('Email ');
        actions.iSeeText('Currenct ');
        actions.iSeeText('Survey ');
        actions.clickOnLink('Resources');
        actions.iSeeText('Dev Resource .2');
      });
      describe('Versioning  - Form Import / Access settings',function(){
        actions.clickOnElementWithText(' Dev ');
        actions.clickOnLink('Forms');
        actions.clickOnClass('.glyphicon.glyphicon-cloud-download');
        actions.enterTextInField('#embedURL','https://basiccomponenttest.form.io/basiccomponents');
        actions.clickOnClass('.form-group.pull-right input');
        actions.enterTextInField('#title','Dev Form .3');
        actions.clickOnElementWithText('Create Form');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText(' Access');
        actions.clickOnClassWithIndex('.ui-select-search',1);
        actions.clickOnElementWithText('Anonymous');
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',3);
        actions.clickOnElementWithText('Administrator');
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',7);
        actions.clickOnElementWithTextIndex('Administrator',1);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',2);
        actions.clickOnElementWithText('Authenticated');
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',5);
        actions.clickOnElementWithTextIndex('Authenticated',1);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.close.ui-select-match-close',5);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.close.ui-select-match-close',5);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',11);
        actions.clickOnElementWithTextIndex('Anonymous',2);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',13);
        actions.clickOnElementWithTextIndex('Anonymous',3);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.ui-select-search',14);
        actions.clickOnElementWithText('Select URL (selectUrl)');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Access');
        actions.clickOnClassWithIndex('.close.ui-select-match-close',2);
      // actions.clickOnClass('.toast-message');
        actions.clickOnClassWithIndex('.close.ui-select-match-close',2);
      // actions.clickOnClass('.toast-message');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnLink('Create Version');
        actions.enterTextInField('#tag', '0.0.4');
        actions.clickOnElementWithText(' Create version');
      // actions.clickOnClass('.toast-message');
        actions.iSeeTextIn('.active .environment-tab .badge', '0.0.4');
        actions.clickOnElementWithText(' Live ');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.selectComponentOption('.tags', '0.0.4');
        actions.clickOnElementWithText(' Deploy version tag to Live');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Forms');
        actions.clickOnElementWithText('Dev Form .3');
        actions.clickOnElementWithText(' Access');
        actions.iSeeTextCount('Anonymous',4);
        actions.iSeeTextCount('Authenticated',2);
        actions.iSeeTextCount('Administrator',2);
        actions.iSeeText('Select URL (selectUrl)');
        actions.clickOnElementWithText('Access');
        actions.iSeeTextCount('Administrator',5);
        actions.clickOnElementWithText(' Dev ');
        actions.clickOnElementWithText('Access');
        // actions.clickOnElementWithText(' New Role');
        // actions.enterTextInField('#title','Test Versioning Role');
        // actions.clickOnElementWithText('Create Role');
        // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText('Forms');
        // actions.clickOnElementWithText('Dev Form .3');
        // actions.clickOnElementWithText(' Access');
        // actions.clickOnClassWithIndex('.ui-select-search',0);
        // actions.clickOnElementWithText('Test Versioning Role');
        // actions.clickOnClass('.toast-message');
        // actions.clickOnClassWithIndex('.ui-select-search',4);
        // actions.clickOnElementWithTextIndex('Test Versioning Role',1);
        // actions.clickOnClass('.toast-message');
        // actions.clickOnLink('Settings');
        // actions.clickOnLink('Stage Version');
        // actions.clickOnLink('Create Version');
        // actions.enterTextInField('#tag', '0.0.5');
        // actions.clickOnElementWithText(' Create version');
        // actions.clickOnClass('.toast-message');
        // actions.iSeeTextIn('.active .environment-tab .badge', '0.0.5');
        // actions.clickOnElementWithText(' Live ');
        // actions.clickOnLink('Settings');
        // actions.clickOnLink('Stage Version');
        // actions.selectComponentOption('.tags', '0.0.5');
        // actions.clickOnElementWithText(' Deploy version to Live');
        // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText('Forms');
        // actions.clickOnElementWithText('Dev Form .3');
        // actions.clickOnElementWithText(' Access');
        // actions.iSeeTextCount('Test Versioning Role',3);
        // actions.clickOnElementWithText(' New Form');
        // actions.clickOnElementWithText('API Web Form');
        // actions.enterTextInField('#title','Dev Form .2');
        // actions.clickOnElementWithText('Create Form');
        // actions.clickOnLink('Resources');
        // actions.clickOnElementWithText(' New Resource');
        // actions.enterTextInField('#title','Dev Resource .2');
        // actions.clickOnElementWithText('Create Resource');
        // actions.clickOnLink('Settings');
        // actions.clickOnLink('Stage Versions');
        // actions.clickOnLink('Create Version');
        // actions.enterTextInField('#tag', '0.0.2');
        // actions.clickOnElementWithText('Create version');
        // actions.waitForActionToComplete(2000);
        // actions.iSeeTextIn('.active .environment-tab .badge', '0.0.2');
        // actions.clickOnElementWithText(' Live ');
        // actions.clickOnLink('Settings');
        // actions.clickOnLink('Stage Versions');
        // actions.selectComponentOption('.tags', '0.0.2');
        // actions.clickOnElementWithText('Deploy version to Live');
        // actions.clickOnLink('Forms');
        // actions.iSeeText('Dev Form .2');
        // actions.clickOnLink('Resources');
        // actions.iSeeText('Dev Resource .2');
      });
      describe('Versioning - Actions ',function(){
        actions.clickOnElementWithText(' Dev ');
        actions.clickOnElementWithText('Settings');
        actions.clickOnElementWithText('Integrations');
        actions.clickOnElementWithText('Data Connections');
        actions.clickOnElementWithText('Hubspot');
        actions.enterTextInField('#apikey','1234');
        actions.clickOnElementWithText('Save Settings');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('SQL Connector');
        actions.enterTextInField('#connectorHost','connectorHost');
        actions.clickOnElementWithText('Select the SQL Type');
        actions.clickOnElementWithText('MySQL');
        actions.enterTextInField('#connectorUser','connectorUser');
        actions.enterTextInField('#connectorPassword','connectorPassword');
        actions.clickOnElementWithText('Save Settings');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Authentication');
        actions.clickOnElementWithText('OAuth');
        actions.clickOnElementWithText('GitHub');
        actions.enterTextInField('#githubClientId','githubClientId');
        actions.enterTextInField('#githubClientSecret','githubClientSecret');
        actions.clickOnElementWithText('Save Settings');
      // actions.clickOnClass('.toast-message');
        actions.clickOnLink('Forms');
        actions.checkingUrlEndsWith('/form/');
        actions.clickOnElementWithText(' New Form');
        actions.clickOnElementWithText('API Web Form');
        actions.enterTextInField('#title','Version Action Test 1');
        actions.dragTo('Button', 'formarea');
        actions.enterTextInField('#label', 'TestOAuth');
        actions.selectOptionWithID('action','OAuth');
        actions.clickOnElementWithText('Save');
        actions.waitForActionToComplete(1000);
        actions.dragTo('Text Field', 'formarea');
        actions.iSeeText('Text Field Component');
        actions.enterTextInField('#label', 'Username');
        actions.clickOnElementWithText('Save');
        actions.waitForActionToComplete(1000);
        actions.dragTo('Password', 'formarea');
        actions.clickOnElementWithText('Save');
        actions.waitForActionToComplete(1000);
        actions.clickOnElementWithText('Create Form');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText(' Actions');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Email');
        actions.clickOnElementWithText(' Add Action');
        actions.enterTextInField('#emails','test@test.com');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Email');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Webhook (Premium)');
        actions.clickOnElementWithText(' Add Action');
        actions.enterTextInField('#url','www.test.com');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Webhook (Premium)');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Role Assignment');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElementWithText('Select the type of resource to perform role manipulation.');
        actions.clickOnElementWithText('Existing Resource');
        actions.clickOnElementWithText('Select whether this Action will Add or Remove the contained Role.');
        actions.clickOnElementWithText('Add Role');
        actions.clickOnElementWithText('Select the Role that this action will Add or Remove.');
        actions.clickOnElementWithText('Administrator');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Role Assignment');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Reset Password');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElement('xpath://*[@id="resources"]/div[1]/input');
        actions.clickOnElementWithText('User');
        actions.clickOnElementWithText('Select the username field');
        actions.clickOnElementWithText('Submit');
        actions.clickOnElementWithText('Select the password field');
        actions.clickOnElementWithTextIndex('Submit',1);
        actions.enterTextInField('#url','www.test.com');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Reset Password');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Login');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElement('xpath://*[@id="resources"]/div[1]/input');
        actions.clickOnElementWithText('User');
        actions.clickOnElementWithText('Select the username field');
        actions.clickOnElementWithText('Submit');
        actions.clickOnElementWithText('Select the password field');
        actions.clickOnElementWithTextIndex('Submit',1);
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Login');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Office 365 Contacts (Premium)');
        actions.clickOnElementWithText(' Add Action');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Office 365 Contacts (Premium)');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Office 365 Calendar (Premium)');
        actions.clickOnElementWithText(' Add Action');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('Office 365 Calendar (Premium)');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Hubspot Contact (Premium)');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        // actions.iSeeText('Hubspot Contact (Premium)');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('OAuth (Premium)');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElementWithText('Select the OAuth Provider');
        actions.clickOnElementWithText('GitHub');
        actions.clickOnElementWithText('Select the action to perform');
        actions.clickOnElementWithText('Remote Authentication');
        actions.clickOnElementWithText('Select the button that triggers OAuth sign-in');
        actions.clickOnElementWithText('TestOAuth');
        actions.clickOnClassWithIndex('.caret.pull-right',3);
        actions.clickOnElementWithText('Administrator');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('OAuth (Premium)');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('LDAP Login (Premium)');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElementWithText('Select which field is the username field');
        actions.clickOnElementWithText('Username');
        actions.clickOnElementWithText('Select which field is the password field');
        actions.clickOnElementWithText('Password');
        actions.clickOnClassWithIndex('.caret.pull-right',2);
        actions.clickOnElementWithText('Administrator');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.iSeeText('LDAP Login (Premium)');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Google Sheets (Premium)');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        // actions.iSeeText('Google Sheets (Premium)');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('SQL Connector (Premium)');
        actions.clickOnElementWithText(' Add Action');
        actions.enterTextInField('#table','table');
        actions.enterTextInField('#primary','primary');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Jira (Premium)');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Group Assignment (Premium)');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElementWithText('Select the Group Resource field');
        actions.clickOnElementWithText('Username');
        actions.clickOnElementWithText('self');
        actions.clickOnElementWithText('Password');
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Select an Action');
        actions.clickOnElementWithText('Moxtra Login');
        actions.clickOnElementWithText(' Add Action');
        actions.clickOnElementWithText('Select the resource we should login against.');
        actions.clickOnElementWithText('Dev Resource .2');
        actions.clickOnElementWithText('Select the first name field');
        actions.clickOnElementWithText('Submit');
        actions.clickOnElementWithText('Select the last name field');
        actions.clickOnElementWithTextIndex('Submit',1);
        actions.waitForActionToComplete(500);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Moxtra Message');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Moxtra Todo');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        // actions.clickOnElementWithText('Select an Action');
        // actions.clickOnElementWithText('Twilio SMS (Premium)');
        // actions.clickOnElementWithText(' Add Action');
        // actions.clickOnElementWithText('Save Action');
        // actions.clickOnClass('.toast-message');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Versions');
        actions.clickOnLink('Create Version');
        actions.checkingUrlEndsWith('/env/staging/create');
        actions.enterTextInField('#tag', '0.0.6');
        actions.clickOnElementWithText(' Create version ');
      // actions.clickOnClass('.toast-message');
        actions.iSeeTextIn('.badge', '0.0.6');
        actions.clickOnElementWithText(' Live ');
        actions.clickOnLink('Settings');
        actions.clickOnLink('Stage Version');
        actions.selectComponentOption('.tags', '0.0.6');
        actions.clickOnElementWithText(' Deploy version tag to Live');
      // actions.clickOnClass('.toast-message');
        actions.iSeeTextIn('.badge', '0.0.6');
        actions.clickOnElementWithText('Forms');
        actions.clickOnElementWithText('Version Action Test 1');
        actions.clickOnElementWithText(' Actions');
        actions.clickOnElementWithText('Group Assignment (Premium)');
        actions.iSeeText('Username');
        actions.iSeeText('Password');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('LDAP Login (Premium)');
        actions.iSeeText('Username');
        actions.iSeeText('Password');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Login');
        actions.iSeeText('User');
        actions.iSeeTextCount('Submit',2);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Role Assignment');
        actions.iSeeText('Existing Resource');
        actions.iSeeText('Add Role');
        actions.iSeeText('Administrator');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Email');
      // actions.clickOnClass('.toast-message');
        actions.iSeeValueIn('#emails','test@test.com');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Webhook (Premium)');
        actions.iSeeValueIn('#url','www.test.com');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Reset Password');
        actions.iSeeText('User');
        actions.iSeeTextCount('Submit',2);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('Office 365 Contacts (Premium)');
        actions.iSeeText('Application Certificate');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('2');
        actions.clickOnElementWithText('Office 365 Calendar (Premium)');
        actions.iSeeText('Application Certificate');
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
        actions.clickOnElementWithText('2');
        actions.clickOnElementWithText('Moxtra Login');
        actions.iSeeText('Dev Resource .2');
        actions.iSeeTextCount('Submit',2);
        actions.clickOnElementWithText('Save Action');
      // actions.clickOnClass('.toast-message');
      });
    });
  });
};
