module.exports = function (actions) {
  describe('Versioning ',function(){
    describe('Test versioning for environments moving up and rolling back',function() {
      actions.logout();
      actions.iAmLoggedInFor('profileuser2');
      actions.goToPage('#/');
      actions.clickOnElementWithText('New Project');
      actions.enterTextInField('#title', 'testProject');
      actions.clickOnElementWithText(' Create Project');
      actions.clickOnLink('Settings');
      actions.clickOnLink('Staging');
      actions.iSeeText('No version tags exist. ');
      actions.clickOnLink('Create Version Tag');
      actions.checkingUrlEndsWith('/env/staging/create');
      actions.enterTextInField('#tag', '0.0.1');
      actions.clickOnElementWithText(' Create version tag');
      actions.clickOnClass('.toast-message');
      actions.iSeeTextIn('.badge', '0.0.1');
      actions.clickOnLink('Staging');
      actions.iSeeText('Select Version Tag');
      actions.clickOnClass('select.form-control');
      actions.iSeeText('0.0.1');
      actions.clickOnElementWithText('+ New Stage');
      actions.enterTextInField('#title', 'Dev');
      actions.clickOnElementWithText(' Add Stage');
      actions.clickOnClass('.toast-message');
      actions.waitForActionToComplete(1000);
      actions.checkingUrlEndsWith('/overview');
      actions.clickOnLink('Settings');
      actions.clickOnLink('Staging');
      actions.iSeeText('Select Version Tag');
      actions.clickOnClass('select.form-control');
      actions.clickOnElementWithTextIndex('0.0.1',1);
      actions.clickOnElementWithText(' Deploy version tag to Dev');
      actions.clickOnClass('.toast-message');
      actions.iSeeTextIn('.badge', '0.0.1');
      actions.clickOnElementWithText(' Deploy version tag to Dev');
      actions.iSeeTextIn(".toast-message",'Please select a tag to deploy.');
      actions.clickOnElementWithText(' Live ');
      actions.clickOnLink('Settings');
      actions.clickOnLink('Staging');
      actions.clickOnLink('Create Version Tag');
      actions.checkingUrlEndsWith('/env/staging/create');
      actions.enterTextInField('#tag', '0.0.3');
      actions.clickOnElementWithText(' Create version tag');
      actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText(' Dev ');
      actions.clickOnLink('Settings');
      actions.clickOnLink('Staging');
      actions.iSeeText('Select Version Tag');
      actions.clickOnClass('select.form-control');
      actions.clickOnElementWithTextIndex('0.0.3',1);
      actions.clickOnElementWithText(' Deploy version tag to Dev');
      actions.clickOnClass('.toast-message');
      actions.iSeeTextIn('.badge', '0.0.3');
      actions.iSeeText('Select Version Tag');
      actions.clickOnClass('select.form-control');
      actions.clickOnElementWithText('0.0.1');
      actions.clickOnElementWithText(' Deploy version tag to Dev');
      actions.clickOnClass('.toast-message');
      // actions.iSeeTextIn('.badge', '0.0.3');
      // actions.clickOnLink('Staging');
      // actions.selectComponentCount('.tags', 3);
      // actions.selectComponentOption('.tags', '0.0.1');
      // actions.clickOnElementWithText('Deploy version tag to Live');
      // actions.waitForActionToComplete(2000);
      // actions.iSeeTextIn('.badge', '0.0.1');
      // actions.clickOnLink('Staging');
      // actions.selectComponentCount('.tags', 3);
      // actions.clickOnElementWithText('+ New Stage');
      // actions.enterTextInField('#title', 'Dev');
      // actions.waitForActionToComplete(2000);
      // actions.clickOnElementWithText(' Add Stage');
      // actions.waitForActionToComplete(2000);
      // actions.clickOnLink('Settings');
      // actions.waitForActionToComplete(2000);
      // actions.clickOnLink('Staging');
      // actions.waitForActionToComplete(2000);
      // actions.selectComponentOption('.tags', '0.0.1');
      // actions.clickOnElementWithText('Deploy version tag to Dev');
      // actions.waitForActionToComplete(2000);
      // actions.iSeeTextIn('.active .environment-tab .badge', '0.0.1');
      // actions.waitForActionToComplete(2000);
    });
    describe('Versioning - Forms / Resources',function(){
      actions.clickOnElementWithText('Forms');
      actions.clickOnClass('.glyphicon.glyphicon-cloud-download');
      actions.enterTextInField('#embedURL','https://struntwrmesxmts.form.io/specialcomponent');
      actions.clickOnClass('.form-group.pull-right input');
      actions.enterTextInField('#title','Dev Form .2');
      actions.clickOnElementWithText('Create Form');
      actions.clickOnClass('.toast-message');
      actions.clickOnLink('Resources');
      actions.clickOnElementWithText(' New Resource');
      actions.enterTextInField('#title','Dev Resource .2');
      actions.clickOnElementWithText('Create Resource');
      actions.clickOnClass('.toast-message');
      actions.clickOnLink('Settings');
      actions.clickOnLink('Staging');
      actions.clickOnLink('Create Version Tag');
      actions.enterTextInField('#tag', '0.0.2');
      actions.clickOnElementWithText(' Create version tag');
      actions.clickOnClass('.toast-message');
      actions.iSeeTextIn('.active .environment-tab .badge', '0.0.2');
      actions.clickOnElementWithText(' Live ');
      actions.clickOnLink('Settings');
      actions.clickOnLink('Staging');
      actions.selectComponentOption('.tags', '0.0.2');
      actions.clickOnElementWithText(' Deploy version tag to Live');
      actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('Forms');
      actions.clickOnElementWithText('Dev Form .2');
      actions.iSeeText('Email ');
      actions.iSeeText('Currenct ');
      actions.iSeeText('Survey ');
      actions.clickOnLink('Resources');
      actions.iSeeText('Dev Resource .2');
    });
    describe('Versioning  - Form Import / Access settings',function(){
      actions.clickOnElementWithText(' Dev ');
      actions.clickOnLink('Forms');
      actions.clickOnClass('.glyphicon.glyphicon-cloud-download');
      actions.enterTextInField('#embedURL','https://basiccomponenttest.form.io/basiccomponents');
      actions.clickOnClass('.form-group.pull-right input');
      actions.enterTextInField('#title','Dev Form .3');
      actions.clickOnElementWithText('Create Form');
      actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText(' Access');
      actions.clickOnClassWithIndex('.ui-select-search',1);
      actions.clickOnElementWithText('Anonymous');
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.ui-select-search',3);
      actions.clickOnElementWithText('Administrator');
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.ui-select-search',7);
      actions.clickOnElementWithTextIndex('Administrator',1);
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.ui-select-search',2);
      actions.clickOnElementWithText('Authenticated');
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.ui-select-search',5);
      actions.clickOnElementWithTextIndex('Authenticated',1);
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.close.ui-select-match-close',5);
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.close.ui-select-match-close',5);
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.ui-select-search',11);
      actions.clickOnElementWithTextIndex('Anonymous',2);
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.ui-select-search',13);
      actions.clickOnElementWithTextIndex('Anonymous',3);
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.ui-select-search',14);
      actions.clickOnElementWithText('Select URL (selectUrl)');
      actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('Access');
      actions.clickOnClassWithIndex('.close.ui-select-match-close',2);
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.close.ui-select-match-close',2);
      actions.clickOnClass('.toast-message');
      actions.clickOnLink('Settings');
      actions.clickOnLink('Staging');
      actions.clickOnLink('Create Version Tag');
      actions.enterTextInField('#tag', '0.0.4');
      actions.clickOnElementWithText(' Create version tag');
      actions.clickOnClass('.toast-message');
      actions.iSeeTextIn('.active .environment-tab .badge', '0.0.4');
      actions.clickOnElementWithText(' Live ');
      actions.clickOnLink('Settings');
      actions.clickOnLink('Staging');
      actions.selectComponentOption('.tags', '0.0.4');
      actions.clickOnElementWithText(' Deploy version tag to Live');
      actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('Forms');
      actions.clickOnElementWithText('Dev Form .3');
      actions.clickOnElementWithText(' Access');
      actions.iSeeTextCount('Anonymous',4);
      actions.iSeeTextCount('Authenticated',2);
      actions.iSeeTextCount('Administrator',2);
      actions.iSeeText('Select URL (selectUrl)');
      actions.clickOnElementWithText('Access');
      actions.iSeeTextCount('Administrator',5);
      actions.clickOnElementWithText(' Dev ');
      actions.clickOnElementWithText('Access');
      actions.clickOnElementWithText(' New Role');
      actions.enterTextInField('#title','Test Versioning Role');
      actions.clickOnElementWithText('Create Role');
      actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('Forms');
      actions.clickOnElementWithText('Dev Form .3');
      actions.clickOnElementWithText(' Access');
      actions.clickOnClassWithIndex('.ui-select-search',0);
      actions.clickOnElementWithText('Test Versioning Role');
      actions.clickOnClass('.toast-message');
      actions.clickOnClassWithIndex('.ui-select-search',4);
      actions.clickOnElementWithTextIndex('Test Versioning Role',1);
      actions.clickOnClass('.toast-message');
      actions.clickOnLink('Settings');
      actions.clickOnLink('Staging');
      actions.clickOnLink('Create Version Tag');
      actions.enterTextInField('#tag', '0.0.5');
      actions.clickOnElementWithText(' Create version tag');
      actions.clickOnClass('.toast-message');
      actions.iSeeTextIn('.active .environment-tab .badge', '0.0.5');
      actions.clickOnElementWithText(' Live ');
      actions.clickOnLink('Settings');
      actions.clickOnLink('Staging');
      actions.selectComponentOption('.tags', '0.0.5');
      actions.clickOnElementWithText(' Deploy version tag to Live');
      actions.clickOnClass('.toast-message');
      actions.clickOnElementWithText('Forms');
      actions.clickOnElementWithText('Dev Form .3');
      actions.clickOnElementWithText(' Access');
      actions.iSeeTextCount('Test Versioning Role',3);
      //
      //
      // actions.clickOnElementWithText(' New Form');
      // actions.clickOnElementWithText('API Web Form');
      // actions.enterTextInField('#title','Dev Form .2');
      // actions.clickOnElementWithText('Create Form');
      // actions.clickOnLink('Resources');
      // actions.clickOnElementWithText(' New Resource');
      // actions.enterTextInField('#title','Dev Resource .2');
      // actions.clickOnElementWithText('Create Resource');
      // actions.clickOnLink('Settings');
      // actions.clickOnLink('Staging');
      // actions.clickOnLink('Create Version Tag');
      // actions.enterTextInField('#tag', '0.0.2');
      // actions.clickOnElementWithText('Create version tag');
      // actions.waitForActionToComplete(2000);
      // actions.iSeeTextIn('.active .environment-tab .badge', '0.0.2');
      // actions.clickOnElementWithText(' Live ');
      // actions.clickOnLink('Settings');
      // actions.clickOnLink('Staging');
      // actions.selectComponentOption('.tags', '0.0.2');
      // actions.clickOnElementWithText('Deploy version tag to Live');
      // actions.clickOnLink('Forms');
      // actions.iSeeText('Dev Form .2');
      // actions.clickOnLink('Resources');
      // actions.iSeeText('Dev Resource .2');
    });
    describe('Versioning - Actions ',function(){
      // actions.clickOnElementWithText(' Dev ');
      // actions.clickOnLink('Forms');
      // actions.checkingUrlEndsWith('/form/');
      // actions.clickOnElementWithText(' New Form');
      // actions.clickOnElementWithText('API Web Form');
      // actions.enterTextInField('#title','Version Action Test 1');
      // actions.clickOnElementWithText('Create Form');
      // actions.clickOnClass('.toast-message');
      // actions.clickOnElementWithText(' Actions');
      // actions.clickOnElementWithText('Select an Action');
      // actions.clickOnElementWithText('Email');
      // actions.clickOnElementWithText(' Add Action');
      // actions.clickOnElementWithText('Select an Action');
      // actions.clickOnElementWithText('Email');
      // actions.clickOnElementWithText(' Add Action');
      // actions.clickOnElementWithText('Select an Action');
      // actions.clickOnElementWithText('Email');
      // actions.clickOnElementWithText(' Add Action');
      // actions.clickOnElementWithText('Select an Action');
      // actions.clickOnElementWithText('Email');
      // actions.clickOnElementWithText(' Add Action');
    });
  });
};
