import '../node_modules/font-awesome/fonts/FontAwesome.otf';
import '../node_modules/font-awesome/fonts/fontawesome-webfont.eot';
import '../node_modules/font-awesome/fonts/fontawesome-webfont.ttf';
import '../node_modules/font-awesome/fonts/fontawesome-webfont.woff';
import '../node_modules/font-awesome/fonts/fontawesome-webfont.woff2';
import '../node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot';
import '../node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf';
import '../node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff';
import '../node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2';
