global.jQuery = require('jquery');
require('angular');
require('angular-ui-mask');
require('ui-select/dist/select');
require('angular-moment');
require('angular-sanitize');
require('signature_pad');
require('angular-file-saver');
require('ng-file-upload');
require('bootstrap');
require('angular-ui-bootstrap');
require('bootstrap-ui-datetime-picker/dist/datetime-picker');
require('./formio');
